name: Maven Action
on: [push]
jobs:
  setup-java-jdk-Maven:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-java@v2
        with:
          distribution: 'zulu' # See 'Supported distributions' for available options
          java-version: '17'
      - name: Build Maven
        run: mvn clean package


